### ISSUE TITLE
Set Interval for TimePicker

### ISSUE THREAD

**Issue by robertbenjamin** [lozjackson/ember-time-tools#1]
Is there a way to set the interval for the time picker to smaller than 30 minutes (eg. 5 minutes or 1 minute)?

Thanks!

**Comment by lozjackson** [comment]
Hi, currently the time is fixed at 30 mins interval.. But it could be changed fairly easily.

There is a 'times' property on the time picker component that returns an array of time objects.  You could easily override this property to return an array of times with a different time interval.

I'm away from a proper internet connection at the moment, on my phone, otherwise I'd update the component to accept a time interval. I will do so when I get back at the end of week... If you can't wait till then you could have a go at overriding the 'times' property yourself.

**Comment by robertbenjamin** [comment]
I found that property and added additional intervals, thanks for your help!

**Comment by lozjackson** [comment]
No problem.. I have added an interval property to the time picker component. ...but I have found that the time picker component takes a long time to render when using small intervals of less than 10 mins. The reason for this is that it uses a component for each time slot which takes some time to render.  So I am refactoring the time picker component to not use components for the time slots - this has improved rendering performance by a large factor.

I should have an update ready tomorrow.

**Comment by robertbenjamin** [comment]
I had a similar problem when I nested for loops to create 5 min intervals, but when I manually added intervals I had no performance issues.

**Comment by lozjackson** [comment]
interesting..

I have made some changes on the `#dev` branch.. this will soon become v0.2.0

There is now a `timeInterval` property on the time picker.

If you would like to test it out that would be great.. I'd appreciate any feedback.

**Comment by lozjackson** [comment]
I have updated the addon to v0.2.0

The `{{time-picker}}` component now has a `timeInterval` property.  The value is minutes.  A value of 30 will produce half-hour intervals.

A value of 10 will produce 10 minute intervals.

```
{{time-picker timeInterval=10}}
```

This is also available on the `{{input-time}}` component.. in this case it is simply passed on to the time-picker component.

```
{{input-time timeInterval=10}}
```

The default value is 30.

**Comment by robertbenjamin** [comment]
Works great, thanks a lot!
